name: www.punjabjewellers.com
favicon: null
layout_spectrum: 0.4061242458410561
typography_spectrum: 0.15201298682950437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7564589146059006
  lightness: 0.7348780771717429
  saturation: 0.36765639134682715
  rhythmicContrast: 0.1868085041642189
purpose: []
