name: www.punjabjewellers.com
favicon: null
layout_spectrum: 0.40462
typography_spectrum: 0.55107
title: PUNJAB JEWELLERS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#42221c'
    - '#fefefe'
    - '#a69592'
    - '#eabd6f'
    - '#754e2a'
  brandStrength: 0.7564589146059006
  lightness: 0.7348780771717429
  saturation: 0.36765639134682715
  rhythmicContrast: 0.1868085041642189
purpose: []
